### ISSUE TITLE
Error extracting Widevine Keys

### ISSUE THREAD

**Issue by Miczys195** [WHTJEON/narrowvine#10]
Are you able to help. I have an error like in the screenshot.

Screen: 
![Screenshot_3](https://user-images.githubusercontent.com/78845122/118479693-a07ff700-b711-11eb-8e86-013ef7f161ce.png)

**Comment by WHTJEON** [comment]
This isn't supposed to happen. That's weird. Is that the full error message? If not, provide me the full error message.

**Comment by Miczys195** [comment]
Yes that is the complete message. I would like to add that the program closes after a while.

**Comment by WHTJEON** [comment]
Try uninstalling completely and download from Releases. The decryption server can be jammed due to traffic so if the problem persists wait for a while and try again. Also, if you send the mpd url and license url, I will test it.

**Comment by Miczys195** [comment]
https://n-16-12.dcs.redcdn.pl/dash/o2/TVP/embeddrm/out/to-byl-rok-1994_bc62f83a6211d5fa73085237c19915aa.mp4/Manifest.ism

https://www.tvp.pl/sess/widevineProxy.php?key=&video_id=53217295

**Comment by WHTJEON** [comment]
> https://n-16-12.dcs.redcdn.pl/dash/o2/TVP/embeddrm/out/to-byl-rok-1994_bc62f83a6211d5fa73085237c19915aa.mp4/Manifest.ism
> 
> https://www.tvp.pl/sess/widevineProxy.php?key=&video_id=53217295

I checked and I am sorry to inform you that your video is incompatible. As you can see it is not in an MPD format, so it does not match the encryption method used in this script. I debugged it and the error was that the key it throws is in an unsupported format.

**Comment by Miczys195** [comment]
https://r.dcs.redcdn.pl/dash/o2/tvnplayer/vod/21_350_28338_0008/SMOOTH_HD_PL/3ba740da-ae44-469e-9d78-b250b49d7b09/playlist.ism/playlist.mpd?indexMode=&dummyfile=

https://player.pl/playerapi/product/drm/widevine
