### ISSUE TITLE
name 'KEY_PROMPT' is not defined

### ISSUE THREAD

**Issue by joostshao** [WHTJEON/narrowvine#17]
trace：
Traceback (most recent call last):
  File "narrowvine.py", line 251, in <module>
    decrypt_content()
  File "narrowvine.py", line 177, in decrypt_content
    parse_key(KEY_PROMPT)
NameError: name 'KEY_PROMPT' is not defined
question： what's the meaning and how to slove it ? 

```
➜  narrowvine git:(main) ✗ python3 narrowvine.py
---------------------------------------------------------------------------------------------------------------------------------------------------------
**** NARROWVINE by vank0n **** (Linux Detected)
---------------------------------------------------------------------------------------------------------------------------------------------------------
Enter MPD URL:
> https://dowuwd6v9jrq0.cloudfront.net/E37EB7-606def4b92c59c2cc4284972/1618935677/607efd760e9b6757d475ba43.mpd
---------------------------------------------------------------------------------------------------------------------------------------------------------
Enter License URL:
> https://licensing.bitmovin.com/licensing
Enter WideVineDecryptor Prompt:
> 2a8b1f24-2c3c-4ab1-adeb-2b89af5171f0
```

**Comment by WHTJEON** [comment]
It clearly says in the README file that extracting keys ONLY works for Windows and you are using linux. If you want to use in linux, you need a Windows machine with a custom CDM installed Chrome with widevine-l3-decryptor extension. It's way more complicated and ultimately you need a Windows Machine so Linux is not supported officially. Use Windows.

**Comment by WHTJEON** [comment]
And by the way, your license url is wrong.
