### ISSUE TITLE
Add support for cookies.txt

### ISSUE THREAD

**Issue by Ashish0804** [WHTJEON/narrowvine#7]

**Comment by WHTJEON** [comment]
Impossible.

**Comment by Ashish0804** [comment]
> Impossible.

why tho? Both ytdlp and requests support cookies.

**Comment by WHTJEON** [comment]
Because downloading the MPD content itself is not the issue. The issue that has to do with cookies is the license_url. There is no easy way to do this, and even if there is, I won't be doing it.
